routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'ArticlesController@index');

Route::resource('articles', 'ArticlesController');
Route::resource('comments', 'CommentsController')->only(['store', 'edit', 'update', 'destroy']);
Route::resource('ratings', 'RatingsController')->only(['store']);

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

app/Comment.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Comment extends Model
{
    protected $fillable = [
        'body',
        'user_id',
        'article_id'
    ];

    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function user()
    {
        return $this->belongsTo(User::class);
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function article()
    {
        return $this->belongsTo(Article::class);
    }
}

app/Http/Controllers/CommentsController.php
<?php

namespace App\Http\Controllers;

use App\Comment;
use App\Http\Requests\CommentRequest;

class CommentsController extends Controller
{
    /**
     * CommentsController constructor.
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * @param CommentRequest $request
     * @return \Illuminate\Http\RedirectResponse|\Illuminate\Routing\Redirector
     */
    public function store(CommentRequest $request)
    {
        $comment = new Comment($request->all());
        $comment->user_id = $request->user()->id;
        $comment->article_id = $request->input('article_id');
        $comment->save();
        $article = $request->input('article_id');
        return redirect(route('articles.show', compact('article')))->with('status', 'You have success create comment');
    }

    /**
     * @param $id
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function edit($id)
    {
        $comment = Comment::findOrFail($id);

        return view('comments.edit', compact('comment'));
    }

    /**
     * @param CommentRequest $request
     * @param $id
     * @return \Illuminate\Http\RedirectResponse|\Illuminate\Routing\Redirector
     * @throws \Illuminate\Auth\Access\AuthorizationException
     */
    public function update(CommentRequest $request, $id)
    {
        $article = $request->input('article_id');
        $comment = Comment::findOrFail($id);
        $this->authorize('update', $comment);
        $comment->update($request->all());

        return redirect(route('articles.show' , compact('article')))->with('status', 'You have success edit comment');
    }

    /**
     * @param $id
     * @return \Illuminate\Http\RedirectResponse|\Illuminate\Routing\Redirector
     * @throws \Illuminate\Auth\Access\AuthorizationException
     */
    public function destroy($id)
    {
        $comment = Comment::findOrFail($id);
        $this->authorize('delete', $comment);
        $comment->delete();

        return back()->with('status', 'You have success remove comment');
    }
}

resources/views/comments/edit.blade.php
@extends('layouts.app')

@section('content')

    <h2>Edit comment</h2>

    <form method="post" action="{{route('comments.update', ['comment' => $comment])}}" class="w-25 mt-5 mb-5">
        @csrf
        @method('put')
        <input type="hidden" id="article_id" name="article_id" value="{{$comment->article->id}}">

        <div class="form-group">
            <label for="body">Comment:</label>
            <textarea class="form-control @error('body') is-invalid @enderror" id="body" name="body" rows="3">{{$comment->body}}</textarea>
            @error('body')
            <p class="text-danger">{{ $message }}</p>
            @enderror
        </div>
        <button type="submit" class="btn btn-success">Edit comment</button>
    </form>

    <div class="mt-3 mb-5">
        <a href="{{route('articles.show', ['article' => $comment->article])}}">Back</a>
    </div>

@endsection