routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'ArticlesController@index');

Route::resource('articles', 'ArticlesController');
Route::resource('comments', 'CommentsController')->only(['store', 'edit', 'update', 'destroy']);
Route::resource('ratings', 'RatingsController')->only(['store']);

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

app/Article.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Article extends Model
{
    protected $fillable = [
        'title',
        'body',
        'user_id',
        'category_id',
        'tag_id',
        'publication_date'
    ];

    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function user()
    {
        return $this->belongsTo(User::class);
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function category()
    {
        return $this->belongsTo(Category::class);
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function tag()
    {
        return $this->belongsTo(Tag::class);
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function ratings()
    {
        return $this->hasMany(Rating::class);
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function comments()
    {
        return $this->hasMany(Comment::class);
    }
}

app/Http/Controllers/ArticlesController.php
<?php

namespace App\Http\Controllers;

use App\Article;
use App\Category;
use App\Http\Requests\ArticleRequest;
use App\Tag;
use Carbon\Carbon;
use Illuminate\Http\Request;

class ArticlesController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function index()
    {
        $articles = Article::where('publication_date', '>=', Carbon::today())->paginate(15);

        return view('articles.index', compact('articles'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function create()
    {
        $categories = Category::all();
        $tags = Tag::all();

        return view('articles.create', compact('categories', 'tags'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param ArticleRequest $request
     * @return \Illuminate\Http\RedirectResponse|\Illuminate\Routing\Redirector
     */
    public function store(ArticleRequest $request)
    {
        $article = new Article($request->all());
        $article->user_id = $request->user()->id;
        $article->save();

        return redirect(route('articles.index'))->with('status', 'Success create article');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function show($id)
    {
        $article = Article::findOrFail($id);
        $comments_count = $article->comments->count();

        return view('articles.show', compact('article', 'comments_count'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function edit($id)
    {
        $article = Article::findOrFail($id);
        $categories = Category::all();
        $tags = Tag::all();

        return view('articles.edit', compact('article', 'categories', 'tags'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @param int $id
     * @return \Illuminate\Http\RedirectResponse|\Illuminate\Routing\Redirector
     * @throws \Illuminate\Auth\Access\AuthorizationException
     */
    public function update(Request $request, $id)
    {
        $article = Article::findOrFail($id);
        $this->authorize('update', $article);
        $article->update($request->all());

        return back()->with('status', 'Success editing News ' . $article->title);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param int $id
     * @return \Illuminate\Http\RedirectResponse|\Illuminate\Routing\Redirector
     * @throws \Illuminate\Auth\Access\AuthorizationException
     */
    public function destroy($id)
    {
        $article = Article::findOrFail($id);
        $this->authorize('delete', $article);
        $article->delete();

        return redirect(route('articles.index'))->with('status', 'Success removed News');
    }
}

resources/views/articles/create.blade.php
@extends('layouts.app')

@section('content')

    <div class="mb-3">
        <h2>Create News</h2>
    </div>

    <form class="w-75 mt-5 mb-5" method="post" action="{{route('articles.store')}}" >
        @csrf
        <div class="form-group">
            <label for="title">Title</label>
            <input type="text" class="form-control @error('title') is-invalid @enderror" id="title" name="title">
            @error('title')
            <p class="text-danger">{{ $message }}</p>
            @enderror
        </div>

        <div class="form-group">
            <label for="body">Text</label>
            <textarea class="form-control @error('body') is-invalid @enderror" id="body" name="body" rows="3"></textarea>
            @error('body')
            <p class="text-danger">{{ $message }}</p>
            @enderror
        </div>

        <div class="form-group">
            <label for="category_id">Category</label>
            <select class="form-control w-25 @error('category_id') is-invalid @enderror" id="category_id" name="category_id">
                @foreach($categories as $category)
                    <option value="{{$category->id}}">{{$category->title}}</option>
                @endforeach
            </select>
        </div>

        <div class="form-group">
            <label for="tag_id">Tag</label>
            <select class="form-control w-25 @error('tag_id') is-invalid @enderror" id="tag_id" name="tag_id">
                @foreach($tags as $tag)
                    <option value="{{$tag->id}}">{{$tag->title}}</option>
                @endforeach
            </select>
        </div>

        @if(Auth::user()->is_admin == true)
            <div class="form-group">
                <label for="publication_date">Title</label>
                <input type="date" class="form-control w-25 @error('publication_date') is-invalid @enderror" id="publication_date" name="publication_date">
                @error('publication_date')
                <p class="text-danger">{{ $message }}</p>
                @enderror
            </div>
        @endif

        <button type="submit" class="btn btn-primary">Create</button>
    </form>

    <div class="mt-3 mb-3">
        <a href="{{route('articles.index')}}">Back</a>
    </div>

@endsection

resources/views/articles/edit.blade.php
@extends('layouts.app')

@section('content')

    <div>
        <h2>Editing News</h2>
    </div>

    <form class="w-75 mt-5 mb-5" method="post" action="{{route('articles.update', ['article' => $article])}}" >
        @csrf
        @method('put')

        <div class="form-group">
            <label for="title">Title</label>
            <input type="text" class="form-control @error('title') is-invalid @enderror" id="title" name="title" value="{{$article->title}}">
            @error('title')
            <p class="text-danger">{{ $message }}</p>
            @enderror
        </div>

        <div class="form-group">
            <label for="body">Text</label>
            <textarea class="form-control @error('body') is-invalid @enderror" id="body" name="body" rows="3">{{$article->body}}</textarea>
            @error('body')
            <p class="text-danger">{{ $message }}</p>
            @enderror
        </div>

        <div class="form-group">
            <label for="category_id">Category</label>
            <select class="form-control w-25 @error('category_id') is-invalid @enderror" id="category_id" name="category_id">
                @foreach($categories as $category)
                    <option value="{{$category->id}}" @if($category->id == $article->category->id) selected @endif>{{$category->title}}</option>
                @endforeach
            </select>
        </div>

        <div class="form-group">
            <label for="tag_id">Tag</label>
            <select class="form-control w-25 @error('tag_id') is-invalid @enderror" id="tag_id" name="tag_id">
                @foreach($tags as $tag)
                    <option value="{{$tag->id}}" @if($tag->id == $article->tag->id) selected @endif>{{$tag->title}}</option>
                @endforeach
            </select>
        </div>

        @can('view', $article)
            <div class="form-group">
                <label for="publication_date">Publication date</label>
                <input type="date" class="form-control w-25 @error('publication_date') is-invalid @enderror" id="publication_date" name="publication_date" value="{{$article->publication_date}}">
                @error('publication_date')
                <p class="text-danger">{{ $message }}</p>
                @enderror
            </div>
        @endcan

        <button type="submit" class="btn btn-primary">Edit</button>
    </form>

    <div class="mt-3 mb-3">
        <a href="{{route('articles.show', ['article' => $article])}}">Back</a>
    </div>

@endsection

resources/views/articles/index.blade.php
@extends('layouts.app')

@section('content')

    <div class="text-center">
        <h2>All News</h2>
    </div>

    <div class="text-right">
        <h3><a href="{{route('articles.create')}}" class="text-success">Create News</a></h3>
    </div>

    <div>
        <ul>
            @foreach($articles as $article)
                <li>
                    <a style="font-size: 20px" href="{{route('articles.show', ['article' => $article])}}">{{$article->title}}</a>
                </li>
            @endforeach
        </ul>
    </div>

    <div class="row p-5">
        <div class="col-12">
            {{ $articles->links() }}
        </div>
    </div>

@endsection

resources/views/articles/show.blade.php
@extends('layouts.app')

@section('content')

    <div class="card">
        <div class="card-header">
            {{$article->title}}
        </div>
        <div class="card-body">
            <p class="card-text text-right text-muted">Author: <a href="">{{$article->user->name}}</a></p>
            <p class="card-text">{{$article->body}}</p>
            <p class="card-text text-muted">Category: <small><a href="">{{$article->category->title}}</a></small></p>
            <p class="card-text text-muted">Tag: <small><a href="">#{{$article->tag->title}}</a></small></p>
            <p class="card-text text-muted text-right">Create: <small>{{$article->created_at->diffForHumans()}}</small></p>
            <p class="card-text text-muted text-right">Publication date: <small>{{$article->publication_date}}</small></p>
        </div>
    </div>

    <div class="text-right">
        @can('update', $article)
            <a href="{{route('articles.edit', ['article' => $article])}}" class="btn btn-success">Edit News</a>
        @endcan

        @can('delete', $article)
            <form class="mt-3" method="post" action="{{route('articles.destroy', ['article' => $article])}}">
                @method('delete')
                @csrf
                <button type="submit" class="btn btn-outline-danger btn-sm">Delete News</button>
            </form>
        @endcan
    </div>

    <div>
        <h3>News score</h3>

        <form method="post" action="{{route('ratings.store')}}" class="w-25 mb-3">
            @csrf
            <input type="hidden" id="article_id" name="article_id" value="{{$article->id}}">

            <div class="form-group">
                <label for="quality">Quality</label>
                <select class="form-control" id="quality" name="quality">
                    <option value="1">Qualitatively</option>
                    <option value="-1">Poor-quality</option>
                </select>
            </div>

            <div class="form-group">
                <label for="relevance">Relevance</label>
                <select class="form-control" id="relevance" name="relevance">
                    <option value="1">Actual</option>
                    <option value="-1">Not actual</option>
                </select>
            </div>

            <div class="form-group">
                <label for="satisfied">Satisfied</label>
                <select class="form-control" id="satisfied" name="satisfied">
                    <option value="1">Satisfied</option>
                    <option value="-1">Dissatisfied</option>
                </select>
            </div>

            <button type="submit" class="btn btn-success">Add feedback</button>
        </form>
    </div>

    <div>
        <button class="show-comments-btn btn btn-info mt-4" type="button" data-toggle="collapse"
                data-target="#comments-block">@lang('Comments'): <span class="comments-number">{{$comments_count}}</span></button>
        <div id="comments-block" class=" collapse multi-collapse mt-5">
            @foreach($article->comments as $comment)
                <div class="card mb-3 w-50">
                    <h5 class="card-header">{{$comment->user->name}}</h5>
                    <div class="card-body">
                        <p class="card-text">{{$comment->body}}</p>
                        <p class="card-text text-right"><small class="text-muted">{{$comment->created_at->diffForHumans()}}</small></p>
                        <div>
                            @can('update', $comment)
                                <hr>
                                <p><a href="{{route('comments.edit', ['comment' => $comment])}}">Edit comment</a></p>
                            @endcan
                            @can('delete', $comment)
                                <form class="mt-3" method="post" action="{{route('comments.destroy', ['comment' => $comment])}}">
                                    @method('delete')
                                    @csrf
                                    <button type="submit" class="btn btn-outline-danger btn-sm">Remove</button>
                                </form>
                            @endcan
                        </div>
                    </div>
                </div>
            @endforeach
        </div>
    </div>

    <form method="post" action="{{route('comments.store')}}" class="w-25 mt-5 mb-5">
        @csrf
        <input type="hidden" id="article_id" name="article_id" value="{{$article->id}}">

        <div class="form-group">
            <label for="body">Comment:</label>
            <textarea class="form-control @error('body') is-invalid @enderror" id="body" name="body" rows="3"></textarea>
            @error('body')
            <p class="text-danger">{{ $message }}</p>
            @enderror
        </div>

        <button type="submit" class="btn btn-success">Add comment</button>
    </form>

    <div class="mt-3 mb-3">
        <a href="{{route('articles.index')}}">Back</a>
    </div>

@endsection